### ISSUE TITLE
Multiple structs by the same name generated

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/yaml-to-go#2]
Example file: https://media.githubusercontent.com/media/ethereum/eth2.0-spec-tests/master/tests/ssz_static/core/ssz_minimal_one.yaml

This has some data like:
```yaml
test_cases:
- Fork:
    value: {previous_version: '0x9f41bd5b', current_version: '0xcbb0f1d7', epoch: 11971467576204192310}
    serialized: '0x9f41bd5bcbb0f1d736eac13f553223a6'
    root: '0x3ad1264c33bc66b43a49b1258b88f34b8dbfa1649f17e6df550f589650d34992'
- Eth1Data:
    value: {deposit_root: '0x05a6e271fd8033f710b2573319885ee3162c386500086d0e4c30badf63642ac5',
      deposit_count: 12713975076169749143, block_hash: '0x372167e6732568f506467486c433b1b0dcd6ae44c317de3bea6ccbd06ad2a8e6'}
    serialized: '0x05a6e271fd8033f710b2573319885ee3162c386500086d0e4c30badf63642ac597924462f81c71b0372167e6732568f506467486c433b1b0dcd6ae44c317de3bea6ccbd06ad2a8e6'
    root: '0x3b5561b7beeeedc120b6c19e22257af9cc32cd598d5afc0ca82923d43f3bf6cf'
```

This creates two `Value` structs. 

```go
type Value struct {
  PreviousVersion string `yaml:"previous_version"`
  CurrentVersion string `yaml:"current_version"`
  Epoch int64 `yaml:"epoch"`
}
type Fork struct {
  Value Value `yaml:"value"`
  Serialized string `yaml:"serialized"`
  Root string `yaml:"root"`
}
type Value struct {
  DepositRoot string `yaml:"deposit_root"`
  DepositCount int64 `yaml:"deposit_count"`
  BlockHash string `yaml:"block_hash"`
}
type Eth1Data struct {
  Value Value `yaml:"value"`
  Serialized string `yaml:"serialized"`
  Root string `yaml:"root"`
}
```

These should be `Fork_Value` and `Eth1Data_Value`. 

https://github.com/mholt/json-to-go/issues/55 was an attempt to resolve this, but doesn't seem to work properly as the expectation here is that the user would manually fix these structs.
